[package]
name = "my-info"
version = "0.4.0"
edition = "2021"
authors = ["Jo√£o Lucas <joaolucasfp2001@gmail.com>"]
license = "MIT"
description = "In this project you will see some information about yourself through the GitHub user"
readme = "README.md"
repository = "https://github.com/joaolfp/MyInfo"
exclude = [".github/**","images/*.png"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
comfy-table = "7.1.1"
futures = "0.3"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.37.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }